### ISSUE TITLE
Build error caused by Uglify.js 

### ISSUE THREAD

**Issue by andreastai** [x-c-f/xcf-webapp#3]
Build completes but with following error

```bash
ERROR in assets/js/vendor.a435be2d15bd1de6c3da.js from UglifyJs

Unexpected token: punc (() [./~/vue-prism/src/index.js:5,0][assets

/js/vendor.a435be2d15bd1de6c3da.js:14231,12]

```

When starting the basexserver with the build js code a blank page pops up. This may be related?

**Comment by micheee** [comment]
…I think we should consider updating most of our JS dependencies.

**Comment by spoeschel** [comment]
This sounds reasonable

**Comment by micheee** [comment]
…we mostly updated to the most recent js dependencies.:)
